 services:
  - type: web
    name: portfolio-dev-agboglo
    env: php
    rootDir: portfolio
    startCommand: "php -S 0.0.0.0:10000 -t ."
    plan: free
    region: frankfurt
    autoDeploy: true

    envVars:
      - key: APP_ENV
        value: production
