 services:
  - type: web
    name: portfolio-dev-agboglo
    env: docker
    rootDir: .
    plan: free
    region: frankfurt
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
